### PR TITLE
[DRAFT, NOPULL] Streaming connection

### PR DESCRIPTION
**Pull request by ben-biddington**
The basics of a working streaming connection.
- timeouts/disconnects not handled
- and tests hang as a result

### CODE REVIEW

**Comment by robert-stuttaford** [comment]
Oh dear. That's right, Rally pulled their own repo for this. Have I unwittingly become the project maintainer? :astonished:

**Comment by ben-biddington** [comment]
Looks like it - do you have clojar publish rights?

**Comment by robert-stuttaford** [comment]
I don't – I must warn you that we forked this repo from Rally and made changes to it to support our own use-case, without ever planning to contribute them back.

I suppose I could ask the Rally folks for clojars access, or otherwise you could maintain a fork of your own.

I don't anticipate that we'll make any further changes to this library, or, in fact, use it for much longer.

I'd hate to cause you to have to go through this process again 6 months from now! :-)

**Comment by ben-biddington** [comment]
Okay, no worries. Why'd they retract theirs?

**Comment by robert-stuttaford** [comment]
They no longer use it, and decided to shutter the repo during a 'clean up'.

**Comment by ben-biddington** [comment]
Bizarre

**Pull request closed without merging**
